### ISSUE TITLE
secretToken for public repository

### ISSUE THREAD

**Issue by amitguptagwl** [opbeat/opbeat-node#115]
Is it fine to have secretToken (as it is) in public github repos? Or should we encrypt them via some tools?

**Comment by watson** [comment]
@amitguptagwl it would allow anyone to send data to your Opbeat app, so it's not something we would recommend. What's your use-case?

**Comment by amitguptagwl** [comment]
I have an open source project [stubmatic](https://github.com/NaturalIntelligence/Stubmatic). As per the guidelines I have added following snippet to the top of my app.

```js
var opbeat = require('opbeat').start({
  appId: '...',
  organizationId: '...',
  secretToken: '...'
})
```
But I can't push the changes because it has secretToken. So I need to remember to remove this snippet before I push any change to gihub. And then add it again.

Or tell me if I'm doing something wrong.

**Comment by watson** [comment]
I would recommend that you handle this the same way you handle all the secret information that your app needs to run. Like for instance database passwords and other API tokens.

Personally I like to put these things in environment variables (Opbeat support using those instead of you giving it an options object). I've also seen people use config files that they don't check into git that contain all the secret stuff. There's also modules like [dotenv](https://www.npmjs.com/package/dotenv).

Regarding using environment variables, if you look at our API docs, you can see that almost all config properties have a corresponding environment variable, e.g `secretToken` can also be set using the environment variable `OPBEAT_SECRET_TOKEN` as is documented here: https://opbeat.com/docs/articles/opbeat-for-nodejs-api/#secrettoken

If you put all your Opbeat config into environment variables, you can just start opbeat like so:

```js
require('opbeat').start()
```

**Comment by watson** [comment]
Then you can update your README with instructions on how to configure the app. You can see an example of an open source app that uses this approach here: https://github.com/opbeat/opbeans#configuration

**Comment by amitguptagwl** [comment]
Thanks @watson . It is really helpful.
