### ISSUE TITLE
Question: Socket closed with active HTTP request (>25 sec)

### ISSUE THREAD

**Issue by adriaanmeuris** [opbeat/opbeat-node#166]
I'm getting a lot of error notifications like this:
```
Socket closed with active HTTP request (>25 sec)
```
I'm seeing this in an endpoint that handles file uploads.

However I'm unable to reproduce this -  I don't have any issues with uploading requests that take up several minutes.

Any idea what could cause this error to pop up? Any guidance where to look would be greatly appreciated.

**Comment by watson** [comment]
This message means that the client aborted the upload. As this is most likely to be expected when dealing with file uploads, you can either [change the threshold](https://opbeat.com/docs/articles/nodejs-agent-api/#timeouterrorthreshold) after which this warning is produced (it defaults to 25 seconds) or you can [disable the warning](https://opbeat.com/docs/articles/nodejs-agent-api/#timeout) all together so that you never see it.

Note that this warning doesn't affect the client at all. This is just Opbeat letting you know that it detected that a client closed their TCP connection prematurely. So it's 100% safe to ignore it if you don't need it.

The reason why we have this warning is because some proxies and routers will terminate long running connections that you either didn't want to have terminated, or that you didn't know you had because of an error in your app. This message will let you debug these issues more easily as it allows you to see during which request this happened.

**Comment by adriaanmeuris** [comment]
Crystal clear - thanks!
