### ISSUE TITLE
Allow to define a custom culprit in opbeat.captureError()

### ISSUE THREAD

**Issue by FdezRomero** [opbeat/opbeat-node#20]
Hi there!

I was trying to send a different **culprit** to Opbeat to better group our custom errors (we can always check for function and filename below in the stacktrace) but I noticed that the module always overrides our `options.culprit`.

Could you add a simple check not to force calling to `setCulprit()` in `lib/parsers.js` when one is already specified?

I was going to write a pull request but I'm not sure how you guys prefer to do this ;-)

Thanks!

**Comment by watson** [comment]
@FdezRomero good idea. I've just released v1.4.0 which now allows you to overwrite the `culprit`

**Comment by FdezRomero** [comment]
Thanks @watson! You were superfast ;-)

**Comment by FdezRomero** [comment]
Hi @watson, I was checking some errors I sent with the custom culprit to Opbeat but they are showing with none in the web (I just see the error group number). I'm sending them like 'opbeat.captureError(err, { culprit: 'This is the culprit', extra: { url: some_url } });`. In the detail page of the error group it says "No culprit available".

Am I doing something wrong?

Thanks.

**Comment by watson** [comment]
@FdezRomero In your case I think the issue is related to that `err` is not an `Error` object but possibly just a string - am I right? There is a bug in v1.4.0 that means that if you just give a string to `captureError` instead of an `Error` object, then it will ignore your custom culprit. This have been fixed in v1.4.1.

But after re-reading your original issue, I see that you are trying to use the culprit to control the grouping inside Opbeat. Unfortunately the culprit is not used to group the errors. Instead I would suggest that you use a custom `Error` object. You can make your own an call then `FooError` and `BarError` or use the default JavaScript error types - each type will then be grouped independently.
