### ISSUE TITLE
Loading environment-variables via dotenv-module

### ISSUE THREAD

**Issue by timoweiss** [opbeat/opbeat-node#37]
The documentation states "It’s important that the Opbeat agent is started before you require any other modules in your Node.js application - i.e. before hapi, before http, even before Babel if you use that."

In our application we use mostly dotenv to load env-vars from a file:

```javascript
require('dotenv').config({path: pathToEnv});
```

So, my question is: Will it break if I require `dotenv` before `opbeat`? Or do I simply get no errors from code above `require('opbeat')`?

thanks in advance for your help :)

**Comment by watson** [comment]
@timoweiss In this particular case you should be perfectly safe requiring `dotenv` before `opbeat. And it shouldn't interfere with the error handler.

The reason why we stress that it should be required and started before anything else is because it's hooking into the Node core to instrument incoming HTTP requests. This will not work if modules like `http` have already been loaded before the `opbeat` module gets a chance to load.

The `dotenv` module doesn't have any dependencies and only require the `fs` module, so it shouldn't be a problem at the moment. But if we ever chose to instrument file system calls, this would interfere with that. But it's not something we currently plan to do.

**Comment by timoweiss** [comment]
perfect :) thanks for the explanation!
