### ISSUE TITLE
Support long stack traces from MySQL module

### ISSUE THREAD

**Issue by AdriVanHoudt** [opbeat/opbeat-node#40]
I reported this is an email a while ago.
Opbeat currently shows the stack trace inside the node mysql lib but that does not help to find where the error came from. 

I would be happy to spend time on this since this is something I/we really want and if you can point me in the right direction that would be great!

**Comment by watson** [comment]
@AdriVanHoudt I just revisited the issue you opened via email. Looking at the stack trace from the logs that you emailed us, it still seems to me like you are using a Node module to capture so called "long stack traces" (like [longjohn](https://github.com/mattinsler/longjohn) or simmilar). As you know, stack traces natively end at the async boundery and does not show anything that happened prior to being de-queued from the event loop. The stack traces reported to Opbeat will only show this.

I have an open bug report in our internal issue tracker on this that I hope to get to soon. But that being said, you are more than welcome to take a stab at this your self. Here's the break down of what happens when an error is captured by the Opbeat agent:

1. The [`captureError`](https://github.com/opbeat/opbeat-node/blob/60bec6762333e7e1ea4db40e937aac6c2aedb4d7/lib/agent.js#L99-L177) function in called with the error
1. That in turn calls [`parseError`](https://github.com/opbeat/opbeat-node/blob/60bec6762333e7e1ea4db40e937aac6c2aedb4d7/lib/parsers.js#L26-L36) which uses the [stackman](https://github.com/watson/stackman) module to parse the actual error
1. The stackman module [uses](https://github.com/watson/stackman/blob/e6530936de87de6a1bc2ed6c6e57f2c77103f453/index.js#L60) the [error-callsites](https://github.com/watson/error-callsites) module to get the callsites (a callsite is the term V8 uses for each frame in a stack trace)
1. Back in the Opbeat module, the `parseError` function calls the [`setStacktrace`](https://github.com/opbeat/opbeat-node/blob/60bec6762333e7e1ea4db40e937aac6c2aedb4d7/lib/parsers.js#L99-L104) function to add the array of callsites returned from the stackman module to the object that's being prepared to be sent to the Opbeat intake API

If this is indeed an error, I expect it to be somewhere in the [error-callsites](https://github.com/watson/error-callsites). Hope this helps :smiley:

**Comment by AdriVanHoudt** [comment]
@watson We don't use one explicitly. I use pretty-error in development but not in production. Let me see if I can make a simple case that would be easier to debug with just mysql (and hapi maybe) in it

**Comment by AdriVanHoudt** [comment]
Ok used:
```js
const Mysql = require('mysql');
const Opbeat = require('opbeat').start({
	"organizationId": "[ID]",
	"appId": "[appId]",
	"secretToken": "[secret]",
	"active": true
});

const pool = Mysql.createPool({
	"host": "localhost",
	"database": "db",
	"user": "root",
	"password": "",
	"multipleStatements": false,
	"connectionLimit": 100
});

pool.getConnection((err, connection) => {

	if (err) {
		throw err;
	}
	
	connection.query('SELECT a FROM b', (err) => {
	
		console.log(err.stack);
		Opbeat.captureError(err);
	});
});
```
result: https://opbeat.com/salesflare/dev/errors/23/c10cc40bf1024e2b8f2040b474ec122f
stack logged with `console.log(err.stack)`
```
Error: ER_NO_SUCH_TABLE: Table 'db.b' doesn't exist
    at Query.Sequence._packetToError (.../node_modules/mysql/lib/protocol/sequences/Sequence.js:48:14)
    at Query.ErrorPacket (.../node_modules/mysql/lib/protocol/sequences/Query.js:83:18)
    at Protocol._parsePacket (.../node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (.../node_modules/mysql/lib/protocol/Parser.js:73:12)
    at Protocol.write (.../node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (.../node_modules/mysql/lib/Connection.js:96:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:529:20)
    at TCP.instrumented [as onread] (.../node_modules/opbeat/lib/instrumentation/async-hooks.js:19:23)
    --------------------
    at Protocol._enqueue (.../node_modules/mysql/lib/protocol/Protocol.js:141:48)
    at PoolConnection.query (.../node_modules/mysql/lib/Connection.js:201:25)
    at .../testing.js:24:13
    at Handshake.onConnect (.../node_modules/mysql/lib/Pool.js:59:7)
    at Handshake.Sequence.end (.../node_modules/mysql/lib/protocol/sequences/Sequence.js:96:24)
    at Handshake.Sequence.OkPacket (.../node_modules/mysql/lib/protocol/sequences/Sequence.js:105:8)
    at Protocol._parsePacket (.../node_modules/mysql/lib/protocol/Protocol.js:280:23)
    at Parser.write (.../node_modules/mysql/lib/protocol/Parser.js:73:12)
    at Protocol.write (.../node_modules/mysql/lib/protocol/Protocol.js:39:16)
    at Socket.<anonymous> (.../node_modules/mysql/lib/Connection.js:96:28)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:529:20)
    at TCP.instrumented [as onread] (.../node_modules/opbeat/lib/instrumentation/async-hooks.js:19:23)
```
(testing.js is the file I used)

**Comment by watson** [comment]
@AdriVanHoudt The line `--------------------` in the middle of your stack trace is common amongst long-stack-trace modules to show where an async call was made. This is where the stack trace would normally end. So it does seem like one of your dependencies is responsible for this.

If you don't mind sharing your dependencies as defined in package.json (either here or via email), I can take a look at which of the dependencies that might cause this.

**Comment by AdriVanHoudt** [comment]
@watson I see but the code I posted is literally what I put in a `testing.js` file and I ran `node testing.js`, I don't see how any other package could be interfering (unless native?)

**Comment by AdriVanHoudt** [comment]
@watson it probably has something to do with https://github.com/felixge/node-mysql/blob/d4a5fd7b5e92a1e09bf3c85d24265eada8a84ad8/lib/protocol/sequences/Sequence.js#L56
;)

**Comment by AdriVanHoudt** [comment]
the problem is if I turn it of (see trace option https://github.com/felixge/node-mysql/blob/13091825e11096748b9273c5b17527c338fec764/Readme.md#connection-options) I wouldn't know where the error occured in my code

**Comment by watson** [comment]
@AdriVanHoudt Ha, nice find :smiley:

As mentioned in the [original commit](https://github.com/felixge/node-mysql/commit/c0e6f278088649084e8936b485ff4c516b2ce69d), the mysql module is not the place to add this feature (I'm a bit surprised this is still in there). But the reason this is "still" not in Node core, as mentioned in the original commit, is because it's adding a considerable overhead to your Node process (between 100x and 10x as far as I know) - since generating a stack trace is very expensive. In this particular case though, it doesn't seem to track the async stack for every async operation. Instead it appears to only happen *if* a certain type of expected error occurs - not for all errors and not for healthy requests - and that's a good thing at least.

So why is this still not used all over the place or even added to Node core? Well, since you can't know ahead of time if an error will occur in a callback, you would need to collect the stack trace before queueing an async task on the Node event loop - just in case it would be needed in the callback. This is the part that's very expensive in terms of CPU time and this would need to happen *every* time something is queued. Therefore it's never recommended to use long stack traces in production.

So this is obviously not something that we can to in the Opbeat agent, as it would add a **huge** overhead to the entire application.

**Comment by AdriVanHoudt** [comment]
@watson nice explanation, it is indeed very nice it is contained since I don't need it anywhere else really! But the stack does contain all the info, it is just not getting parsed by Opbeat, or am I missing the ball here?

**Comment by watson** [comment]
@AdriVanHoudt The mysql module [overwrites the `stack` property](https://github.com/felixge/node-mysql/blob/8189925374e7ce3819bbe88b64c7b15abac96b16/lib/protocol/sequences/Sequence.js#L44) of the Error object. The opbeat module doesn't use the stack property for anything but instead hooks into the [V8 stack trace API](https://github.com/v8/v8/wiki/Stack-Trace-API) since this gives more in-depth details of the errror. Hence, the Opbeat module don't see the hacked stack trace string generated by mysql

**Comment by AdriVanHoudt** [comment]
@watson I see, so where does this go from here? Opbeat hacks into the mysql module? (it would be cool in general to see the impact of queries in opbeat like it shows the impact of api requests) Opbeat detects mysql module and then does some error.stack magic? or?

**Comment by watson** [comment]
@AdriVanHoudt The best solution that I can currently come up with is for Opbeat to also log the raw stack trace string from the `stack` property. There is currently no place in the Opbeat UI to show this, so it would be something that our product team would need to take a look at. I'll make sure we take this into consideration, but I can obviously not make any promises.

**Comment by AdriVanHoudt** [comment]
@watson no problem, this would mean it doesn't parse like the stacks do now right? Where I can immediately see the code linked to it? 
Also is there an intent to measure db impact like shown in the activity breakdown at https://opbeat.com/nodejs/ for mysql queries?

**Comment by watson** [comment]
@AdriVanHoudt Yes, performance metrics for mysql is in the works and currently scheduled as our next big Node.js feature.

Are you asking about the code that extracts the callsites from errors? For that we use the [error-callsites](https://github.com/watson/error-callsites) module.

**Comment by AdriVanHoudt** [comment]
Ow nice! looking forward to that.

And yeah but it would be weird to add a case in the module to support Mysql stack traces that are not v8 traces...
Logging the stack trace as plain text and making it visible with the error would already help a lot though

**Comment by AdriVanHoudt** [comment]
btw as suggestion it would very cool to be able to see what query/route Mysql has the most impact on

**Comment by AdriVanHoudt** [comment]
After some usage it is way more manageable now but I still can't see a decent stack trace and some different errors still get put into the same error on Opbeat. I know this will probably be a hacky fix but if not impossible you have a +1 from me 👍 since it will greatly improve my debugging experience

**Comment by watson** [comment]
Opbeat has joined forces with [Elastic](https://www.elastic.co) and this agent is therefore deprecated. So I'll go ahead and close this issue.

Our new product is called [Elastic APM](https://www.elastic.co/solutions/apm), it's open source, and the [Node.js agent](https://github.com/elastic/apm-agent-nodejs) used there is based off this agent. If you're interested in trying out Elastic APM, we'd love your [feedback](https://discuss.elastic.co/c/apm).

We have not yet implemented any special handling of long stack traces in the Elastic APM Node.js Agent, but if you like to bring it up again, you're welcome to open a [feature request](https://github.com/elastic/apm-agent-nodejs/issues/new?template=Feature_request.md).
