### ISSUE TITLE
Conditional reporting

### ISSUE THREAD

**Issue by snird** [opbeat/opbeat-node#71]
Is it possible to have conditional reporting? Meaning, to decide when not to send reports to opbeat?

For example, we have pull notifications api, which is accessed by every user multiple times in just one second. Having this in the reports, will bloat up our package immediately.

**Comment by watson** [comment]
@snird in the latest version of the agent, it's possible to ignore [certain routes](https://opbeat.com/docs/articles/opbeat-for-nodejs-api/#ignoreurls) or [certain user agents](https://opbeat.com/docs/articles/opbeat-for-nodejs-api/#ignoreuseragents) so that they are not sent as metrics to Opbeat.

Please let me know if this answers your question 😃

**Comment by snird** [comment]
Yes. this is perfect. thanks!
