### ISSUE TITLE
Allow disabling instrumentation for specific modules, such as crypto

### ISSUE THREAD

**Issue by rgrove** [opbeat/opbeat-node#83]
Opbeat currently instruments the `pbkdf2`, `pseudoRandomBytes`, and `randomBytes` methods  on the `crypto` module by [replacing them with wrapper functions](https://github.com/opbeat/opbeat-node/blob/d91ddde43c093dbe8126d7a1ce21e6bb1e7701c3/lib/instrumentation/async-hooks.js#L260-L273), and crashes if it can't add this instrumentation, for example if `crypto` has been frozen with `Object.freeze()`:

```
./node_modules/opbeat/lib/instrumentation/shimmer.js:48
  nodule[name] = wrapped
               ^

TypeError: Cannot assign to read only property 'pbkdf2' of object '#<Object>'
    at wrap (./node_modules/opbeat/lib/instrumentation/shimmer.js:48:16)
    at ./node_modules/opbeat/lib/instrumentation/shimmer.js:69:7
    at Array.forEach (native)
    at ./node_modules/opbeat/lib/instrumentation/shimmer.js:68:11
    at Array.forEach (native)
    at massWrap (./node_modules/opbeat/lib/instrumentation/shimmer.js:67:11)
    at module.exports (./node_modules/opbeat/lib/instrumentation/async-hooks.js:264:5)
    at Instrumentation.start (./node_modules/opbeat/lib/instrumentation/index.js:30:27)
    at Agent.start (./node_modules/opbeat/lib/agent.js:105:25)
    at Object.<anonymous> (./server/lib/opbeat.js:4:34)
```

While I generally trust opbeat, I'd really prefer not to allow it (or any third party code I use) to modify the `crypto` module in any way.

Please consider adding a config option that would allow me to prevent opbeat from instrumenting specific modules. Or, alternatively, allow me to specify a whitelist of modules that I _do_ want opbeat to instrument.

**Comment by AdriVanHoudt** [comment]
If you don't warp them don't you lose the trace?

**Comment by rgrove** [comment]
Yes. I'm fine with that.

**Comment by watson** [comment]
@rgrove You can disable this by setting the `instrument` option to `false`: https://opbeat.com/docs/articles/opbeat-for-nodejs-api/#instrument

Can I ask what makes you freeze the `crypto` object? Is it for security reasons and at what point in your app-boot sequence does it happen?

**Comment by rgrove** [comment]
@watson I do want to instrument _most_ things. Just not `crypto`. Right now I've disabled instrumentation, but this means opbeat is only useful for capturing errors. I'd love to be able to get performance metrics too (but I don't need or want performance metrics for `crypto`).

> Can I ask what makes you freeze the `crypto` object? Is it for security reasons and at what point in your app-boot sequence does it happen?

Yes, it's for security reasons.

Imagine that someday an overworked maintainer of one of my npm dependencies (or one of my dependencies' dependencies) accepts a pull request without giving it a completely thorough review, and buried deep in the contributed code is something like this:

```js
require('crypto').randomBytes = (size, cb) => {
  let buf = Buffer.from('a'.repeat(size));
  return cb ? void cb(null, buf) : buf;
};
```

Now `randomBytes()` is returning completely non-random bytes, but users of the method may never notice since its output is still valid. Any "random" bytes I generate during this period are tainted, and anything I derive from those bytes and store is also tainted, but it could be weeks or months before I notice. By that time, I'll have no good way of knowing just how much tainted data I have on my hands.

To mitigate something like this, I freeze `crypto` before I require any third-party modules (including opbeat). So my `index.js` looks something like this:

```js
#!/usr/bin/env node
'use strict';

Object.freeze(require('crypto'));

// ...start requiring modules...
```

I realize there are many other ways a malicious dependency could wreak havoc, but few would be as subtle or as potentially damaging to my business in the long term as this one, which is why I'm particularly paranoid about it.

**Comment by watson** [comment]
@rgrove Thanks for the feedback. While I do understand your concern, I'm afraid there isn't much we can do to give you instrumentation support and not patch crypto at the same time.

To be able to instrument your codebase we need to patch every async opperation. Without that we wont be able to know which HTTP request was responsible for a given database query etc. And if we don't know that, we can't really give you any insights into the performance of your code. So even though we don't directly show you traces for how long it takes to run those crypto functions, it's still important that we can patch them to track HTTP requests across their async boundaries.

**There is one tiny option we could try though.** Since you freeze the entire crypto module - but we only patch these three async functions: `pbkdf2`, `randomBytes`, and `pseudoRandomBytes` - we could (if you or any dependency of yours don't actually use any of those during the request/response life-cycle) make an experimental feature flag to *not* patch those. That would solve this for your scenario. But I have to stress that if that feature flag is used and one of those three functions are called during the request/response life-cycle - Instrumentation and error handling will start reporting wrong or untrustworthy data.

Would that work in your case, or do you depend on `pbkdf2`, `randomBytes`, or `pseudoRandomBytes` during the request/response life-cycle?

**Comment by rgrove** [comment]
> To be able to instrument your codebase we need to patch every async opperation. Without that we wont be able to know which HTTP request was responsible for a given database query etc.

That's interesting. Thanks for explaining.

> Would that work in your case, or do you depend on `pbkdf2`, `randomBytes`, or `pseudoRandomBytes` during the request/response life-cycle?

Unfortunately I do use `randomBytes` extensively on most requests, and `pbkdf2` on some as well.

Sounds like what I want isn't going to be possible, but thanks for the consideration and the info. 👍

**Comment by watson** [comment]
@rgrove Sorry there isn't much we can do. When the AsyncHooks Node.js API lands, we might able to support this. I'll put in the backlog for when that happens.

**Comment by watson** [comment]
Opbeat has joined forces with [Elastic](https://www.elastic.co) and this agent is therefore deprecated. So I'll go ahead and close this issue.

Our new product is called [Elastic APM](https://www.elastic.co/solutions/apm), it's open source, and the [Node.js agent](https://github.com/elastic/apm-agent-nodejs) used there is based off this agent. AsyncHooks support have been added to the Elastic APM Node.js Agent, so if you're interested in trying out Elastic APM, we'd love your [feedback](https://discuss.elastic.co/c/apm).
