### ISSUE TITLE
Profiling Question

### ISSUE THREAD

**Issue by iCyberon** [opbeat/opbeat-node#92]
Hey @watson 

Have a question regarding CPU profiling. I'm not sure what's going on, but looks like ```instrumented``` (```line 108 in instrumentation/index.js```) is taking too much time. Though, I think, it's the original function which takes that time and it's just my paranoia.

Anyway, just wanted to check with you and move forward :)

**Comment by watson** [comment]
@iCyberon you are referring to [this function](https://github.com/opbeat/opbeat-node/blob/d4f3db0ea931ac6562ece4fb18b9dccdb61cc00d/lib/instrumentation/index.js#L108-L114) right?

That function shouldn't take any time at all, unless you of cause are also counting the time spend calling functions deeper in the stack as well.

That function is the basic wrapper function that is used as a wrapper around all the code we instrument. So if the code we instrument takes 5ms to run, this function will also take around 5ms to run. Does that make sense?

Which tool are you using for profiling? I'll be happy to take a look if you have some output to share :)

**Comment by iCyberon** [comment]
@watson Thanks man! 

Yup, I was referring to the total time, not self time. Just wanted to check with you. I'm using Chrome to visualize the cpuprofile dump file. It's a little bit confusing because Chrome shows that ```instrumented``` is the deepest function in the stack (not always). Guess that might happen because of ```nextTick...```.

Thanks 👍

**Comment by watson** [comment]
Even if it's just calling `nextTick`, I'd imagine that you should see that in the dump file. I'll try and take a look my self. But I can't imagine the self-time of that function to take any meaningful amount of time since it's just swapping references of two objects.

We always work on optimizing our code base - especially hot pieces of code like this one. So please keep sending us questions like this as I'll happily look it over 😃
