### ISSUE TITLE
Add ability to silence network related agent errors

### ISSUE THREAD

**Issue by iCyberon** [opbeat/opbeat-node#94]
Just got another error. I think it would be much, much better to just disable all opbeat network related errors while environment is set to production, or at least make it configurable. In my case I receive email alert every time something is written to stdout and believe me you don't want to receive an email at 4 am just because of DNS timeout which happened inside opbeat :) 

```
App 55807 stderr: Could not notify Opbeat { uuid: undefined }
App 55807 stderr: Error: getaddrinfo EAI_AGAIN intake.opbeat.com:443
App 55807 stderr:     at Object.exports._errnoException (util.js:907:11)
App 55807 stderr:     at errnoException (dns.js:32:15)
App 55807 stderr:     at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:78:26)
```

**Comment by watson** [comment]
Sorry to hear that. I think it's just the name server you asked that had a hiccup:

> EAI_AGAIN actually means a temporary failure in name resolution or simply the name server returned a temporary failure indication.

\- From http://www.codingdefined.com/2015/06/nodejs-error-errno-eaiagain.html

I'll mark this as an enhancement request to allow the user to silence these sort of errors.

**Comment by watson** [comment]
Opbeat has joined forces with [Elastic](https://www.elastic.co) and this agent is therefore deprecated. So I'll go ahead and close this issue.

Our new product is called [Elastic APM](https://www.elastic.co/solutions/apm), it's open source, and the [Node.js agent](https://github.com/elastic/apm-agent-nodejs) used there is based off this agent. Large parts of the source code have been rewritten since then - including the logging part, so this might have been "fixed" there already. If you're interested in trying out Elastic APM, we'd love your [feedback](https://discuss.elastic.co/c/apm).
